#!/usr/bin/env bash
set -euo pipefail
# Generates Round2 explanations using prompts/round2/*.json
# Usage examples:
#   TOP_N=3 ONLY_MAJOR=AI ONLY_VARIANT=baseline_round2 bash generate_r2_responses.sh
#   TOP_N=10 bash generate_r2_responses.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GEN_PY="$SCRIPT_DIR/data/response_generator.py"
JUDGED_DIR="$SCRIPT_DIR/data/judged_dataset"
OUT_DIR="$SCRIPT_DIR/data/response_dataset"

# Round2 prompt files (generated by prompts/prompt_round2.py or optimize_prompts_round2.py)
P_BASE="$SCRIPT_DIR/prompts/round2/baseline_round2.json"
P_L2="$SCRIPT_DIR/prompts/round2/level2_round2.json"
P_L3="$SCRIPT_DIR/prompts/round2/level3_round2.json"

TOP_N="${TOP_N:-10}"                  # default 10
ONLY_MAJOR="${ONLY_MAJOR:-}"          # e.g. AI / cs / stats (match filename)
ONLY_VARIANT="${ONLY_VARIANT:-}"      # e.g. baseline_round2 / level2_round2 / level3_round2

# Check prompt files exist
for p in "$P_BASE" "$P_L2" "$P_L3"; do
  if [ ! -f "$p" ]; then
    echo "❌ Missing Round2 prompt file: $p"
    echo "   Run: python3 prompts/prompt_round2.py"
    exit 1
  fi
done

echo "✅ Found Round2 prompt files."
echo ""

# Map variant -> prompt file
declare -A VARIANT_PROMPT=(
  ["baseline_round2"]="$P_BASE"
  ["level2_round2"]="$P_L2"
  ["level3_round2"]="$P_L3"
)

# Which variants to run
variants=("baseline_round2" "level2_round2" "level3_round2")
if [ -n "$ONLY_VARIANT" ]; then
  variants=("$ONLY_VARIANT")
fi

# Iterate judged_dataset/*_results.jsonl (NOT response_dataset)
shopt -s nullglob
judged_files=( "$JUDGED_DIR"/*_results.jsonl )
shopt -u nullglob

if [ ${#judged_files[@]} -eq 0 ]; then
  echo "❌ No judged *_results.jsonl found in: $JUDGED_DIR"
  exit 1
fi

for jf in "${judged_files[@]}"; do
  base="$(basename "$jf")"  # e.g. glossary_of_AI_results.jsonl

  if [ -n "$ONLY_MAJOR" ]; then
    # crude filter: require ONLY_MAJOR token appears in filename
    if [[ "$base" != *"$ONLY_MAJOR"* ]]; then
      continue
    fi
  fi

  # output name: glossary_of_AI_explanations.jsonl
  out_name="${base/_results/_explanations}"

  for v in "${variants[@]}"; do
    prompt_file="${VARIANT_PROMPT[$v]}"
    out_dir="$OUT_DIR/$v"
    mkdir -p "$out_dir"
    out_path="$out_dir/$out_name"

    echo "=============================="
    echo "Major file: $base"
    echo "Variant:    $v"
    echo "Top N:      $TOP_N"
    echo "Prompt:     $prompt_file"
    echo "Input:      $jf"
    echo "Output:     $out_path"
    echo "=============================="

    python3 "$GEN_PY" \
      --input "$jf" \
      --output "$out_path" \
      --prompt-file "$prompt_file" \
      --top "$TOP_N" \
      --no-tag

    echo "✅ wrote $out_path"
    echo ""
  done
done

echo "✅ Round2 generation complete."
